VerboseFilter() : handle non-string log messages
It looks like the logger can be called with a non-string
object as a message; this resulted today in a failure
in VerboseFilter:

    if record.msg.startswith('>'):
  AttributeError: 'exceptions.IndexError' object has no attribute 'startswith'

Solution: use getMessage() instead of directly accessing
the .msg element; that should reliably give us a string.

Add test.

Signed-off-by: Ed Santiago <santiago@redhat.com>